feat:verificar coverahe

diff --git a/.github/workflows/maven-despliegue-fallos.yml b/.github/workflows/maven-despliegue-fallos.yml
--- a/.github/workflows/maven-despliegue-fallos.yml
+++ b/.github/workflows/maven-despliegue-fallos.yml
@@ -58,9 +58,6 @@ jobs:
             exit 1
           fi 
 
-      
-
-
       - name: Comment on PR with coverage percentages
         if: ${{ github.event_name == 'pull_request' }}
         run: |
@@ -79,9 +76,10 @@ jobs:
           echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
           echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
 
-      
-
-      
-
-     
-        
+      - name: Coverage CheckOut
+        run: |
+          COVERAGE=$(echo "${{ steps.jacoco.outputs.coverage }}" | tr -d '%')
+          if [ "$COVERAGE" -lt 60 ]; then
+            echo "Code coverage is below 60%, setting workflow status to failure."
+            exit 1
+          fi    
